### ISSUE TITLE
Не получается сделать make с исходниками

### ISSUE THREAD

**Issue by kirkokuev** [ZigFisher/Glutinium#2]
При запуске команды make на роутере выдается следующий ответ
`Makefile:17: /package.mk: No such file or directory
make: *** No rule to make target '/package.mk'.  Stop.
r`

**Comment by ZigFisher** [comment]
Все представленные пакеты сделаны для сборки в среде OpenWrt.
Данный репозиторий подключается в OpenWrt как отдельный feed.
Работа с пакетами вне среды OpenWrt возможна, но не гарантируется.

**Comment by kirkokuev** [comment]
Скачал исходники openwrt, последняя версия из гита. Сделал 
```
make tools/install
make toolchain/install
```
Выполнил команды по добавлению фидов 

```
cd OpenWRT
mkdir glutinium
echo "src-git glutinium https://github.com/ZigFisher/Glutinium.git" >./feeds.conf  # if not have it in feeds.conf
./scripts/feeds update glutinium       # or ./scripts/feeds update -a
./scripts/feeds install i2c-telemetry  # or ./scripts/feeds install -a

make menuconfig                        # select i2c-telemetry in utils dir

```
Далее при попытке сборки пакета, наблюдаю следующие ошибки

```
WARNING: Makefile 'package/feeds/glutinium/accel-ppp/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/feeds/glutinium/darkice/Makefile' has a dependency on 'lame-lib', which does not exist
WARNING: Makefile 'package/feeds/glutinium/estgb/Makefile' has a build dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/flypeek/Makefile' has a dependency on 'libjpeg', which does not exist
WARNING: Makefile 'package/feeds/glutinium/flypeek/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/i2c-tools/Makefile' has a dependency on 'python-mini', which does not exist
WARNING: Makefile 'package/feeds/glutinium/i2c-tools/Makefile' has a build dependency on 'python', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/feeds/glutinium/microbe-web/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-cli/Makefile' has a dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-cli/Makefile' has a build dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-tinny/Makefile' has a build dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/network/utils/nftables/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/glutinium/tg-web/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/uvc-ctrl/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/uvc2http/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/webadmin/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/webadmin/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/zabbix-uci/Makefile' has a dependency on 'libsqlite3', which does not exist
WARNING: Makefile 'package/feeds/glutinium/zabbix-uci/Makefile' has a dependency on 'libsqlite3', which does not exist
 make[1] package/megatec/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C feeds/glutinium/megatec compile
make -r package/megatec/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/kkokuev/OpenWRT/openwrt/include/toplevel.mk:216: recipe for target 'package/megatec/compile' failed
make: *** [package/megatec/compile] Error 1

```
C детализацией процесс компиляции выдает гору ошибок
```
WARNING: Makefile 'package/feeds/glutinium/accel-ppp/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a dependency on 'libpam', which does not exist
WARNING: Makefile 'package/utils/busybox/Makefile' has a build dependency on 'libpam', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libgnutls', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libopenldap', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libidn2', which does not exist
WARNING: Makefile 'package/network/utils/curl/Makefile' has a dependency on 'libssh2', which does not exist
WARNING: Makefile 'package/feeds/glutinium/darkice/Makefile' has a dependency on 'lame-lib', which does not exist
WARNING: Makefile 'package/feeds/glutinium/estgb/Makefile' has a build dependency on 'libcurl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/flypeek/Makefile' has a dependency on 'libjpeg', which does not exist
WARNING: Makefile 'package/feeds/glutinium/flypeek/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/i2c-tools/Makefile' has a dependency on 'python-mini', which does not exist
WARNING: Makefile 'package/feeds/glutinium/i2c-tools/Makefile' has a build dependency on 'python', which does not exist
WARNING: Makefile 'package/boot/kexec-tools/Makefile' has a dependency on 'liblzma', which does not exist
WARNING: Makefile 'package/network/services/lldpd/Makefile' has a dependency on 'libnetsnmp', which does not exist
WARNING: Makefile 'package/feeds/glutinium/microbe-web/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-cli/Makefile' has a dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-cli/Makefile' has a build dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/feeds/glutinium/modbus-tinny/Makefile' has a build dependency on 'libmodbus', which does not exist
WARNING: Makefile 'package/network/utils/nftables/Makefile' has a dependency on 'jansson', which does not exist
WARNING: Makefile 'package/feeds/glutinium/tg-web/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/uvc-ctrl/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/uvc2http/Makefile' has a dependency on 'libv4l', which does not exist
WARNING: Makefile 'package/feeds/glutinium/webadmin/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/webadmin/Makefile' has a dependency on 'haserl', which does not exist
WARNING: Makefile 'package/feeds/glutinium/zabbix-uci/Makefile' has a dependency on 'libsqlite3', which does not exist
WARNING: Makefile 'package/feeds/glutinium/zabbix-uci/Makefile' has a dependency on 'libsqlite3', which does not exist
make[1]: Entering directory '/home/kkokuev/OpenWRT/openwrt'
make[2]: Entering directory '/home/kkokuev/OpenWRT/openwrt/package/libs/toolchain'
echo "libc" >> /home/kkokuev/OpenWRT/openwrt/staging_dir/target-mipsel_24kc_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/kkokuev/OpenWRT/openwrt/staging_dir/target-mipsel_24kc_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/kkokuev/OpenWRT/openwrt/staging_dir/target-mipsel_24kc_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/kkokuev/OpenWRT/openwrt/package/libs/toolchain'
time: package/libs/toolchain/compile#0.03#0.00#0.10
make[2]: Entering directory '/home/kkokuev/OpenWRT/openwrt/feeds/glutinium/megatec'
rm -f /home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/.built
touch /home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/.built_check
mipsel-openwrt-linux-musl-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01:megatec-2018-10-01 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -L/home/kkokuev/OpenWRT/openwrt/staging_dir/target-mipsel_24kc_musl/usr/lib -L/home/kkokuev/OpenWRT/openwrt/staging_dir/target-mipsel_24kc_musl/lib -L/home/kkokuev/OpenWRT/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/usr/lib -L/home/kkokuev/OpenWRT/openwrt/staging_dir/toolchain-mipsel_24kc_gcc-7.4.0_musl/lib -znow -zrelro -O -g -D LINUX -o /home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec /home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c: In function 'main':
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c:117:17: warning: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
                 strncpy(Params,&buf[0],50);
                 ^~~~~~~
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c:117:17: warning: incompatible implicit declaration of built-in function 'strncpy'
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c:117:17: note: include '<string.h>' or provide a declaration of 'strncpy'
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c:128:21: error: format not a string literal and no format arguments [-Werror=format-security]
                     printf(err_str);
                     ^~~~~~
/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/megatec_v4.c:140:17: error: format not a string literal and no format arguments [-Werror=format-security]
                 printf(err_str);
                 ^~~~~~
cc1: some warnings being treated as errors
Makefile:46: recipe for target '/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/.built' failed
make[2]: *** [/home/kkokuev/OpenWRT/openwrt/build_dir/target-mipsel_24kc_musl/megatec-2018-10-01/.built] Error 1
make[2]: Leaving directory '/home/kkokuev/OpenWRT/openwrt/feeds/glutinium/megatec'
time: package/feeds/glutinium/megatec/compile#0.05#0.01#0.12
package/Makefile:107: recipe for target 'package/feeds/glutinium/megatec/compile' failed
make[1]: *** [package/feeds/glutinium/megatec/compile] Error 2
make[1]: Leaving directory '/home/kkokuev/OpenWRT/openwrt'
/home/kkokuev/OpenWRT/openwrt/include/toplevel.mk:216: recipe for target 'package/megatec/compile' failed
make: *** [package/megatec/compile] Error 2

```

**Comment by kirkokuev** [comment]
А почему закрыли баг? Пакет не собирается из-за ошибок в коде, стоило бы их поправить.

**Comment by ZigFisher** [comment]
> А почему закрыли баг? Пакет не собирается из-за ошибок в коде, стоило бы их поправить.

1. Потому что никакого бага нет (логи сборки прилагаются)
2. Потому что отправил вам бинарные сборки по вашей просьбе под ваш процессор и не получил абсолютно никакого фидбека

P.S. Утилита собирается под всеми поддерживаемыми мною платформами, от Ralink до Hisilicon

zig@octopus:~/chaos_calmer$  make package/feeds/glutinium/megatec/{clean,compile,install}

 make[1] package/feeds/glutinium/megatec/clean
 make[2] -C feeds/glutinium/megatec clean
 make[1] package/feeds/glutinium/megatec/compile
 make[2] -C package/libs/toolchain compile
 make[2] -C feeds/glutinium/megatec compile
 make[1] package/feeds/glutinium/megatec/install
 make[2] -C feeds/glutinium/megatec install

zig@octopus:~/chaos_calmer$ make -j 1 V=s package/feeds/glutinium/megatec/{clean,compile,install}
make[1]: Entering directory `/home/zig/chaos_calmer'
make[2]: Entering directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
rm -f /home/zig/chaos_calmer/bin/hisilicon/packages/glutinium/megatec_*
rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/stamp/.megatec_installed
rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/packages/megatec.list /home/zig/chaos_calmer/staging_dir/host/packages/megatec.list
rm -rf /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01
make[2]: Leaving directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
make[1]: Leaving directory `/home/zig/chaos_calmer'
make[1]: Entering directory `/home/zig/chaos_calmer'
make[2]: Entering directory `/home/zig/chaos_calmer/package/libs/toolchain'
if [ -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libc" >> /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libgcc" >> /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libstdcpp" >> /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "libpthread" >> /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
if [ -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean ]; then rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install.clean; fi; echo "librt" >> /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo/toolchain.default.install
make[2]: Leaving directory `/home/zig/chaos_calmer/package/libs/toolchain'
make[2]: Entering directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
install -d -m0755 /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01
install -m0644 ./src/* /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/
touch /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/.prepared_fd31537dee6a220352ee6730c70291b7
rm -f /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/stamp/.megatec_installed
(cd /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/./; if [ -x ./configure ]; then find /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ -name config.guess | xargs -r chmod u+w; find /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ -name config.guess | xargs -r -n1 cp --remove-destination /home/zig/chaos_calmer/scripts/config.guess; find /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ -name config.sub | xargs -r chmod u+w; find /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ -name config.sub | xargs -r -n1 cp --remove-destination /home/zig/chaos_calmer/scripts/config.sub; AR="arm-openwrt-linux-uclibcgnueabi-gcc-ar" AS="arm-openwrt-linux-uclibcgnueabi-gcc -c -Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft" LD=arm-openwrt-linux-uclibcgnueabi-ld NM="arm-openwrt-linux-uclibcgnueabi-gcc-nm" CC="arm-openwrt-linux-uclibcgnueabi-gcc" GCC="arm-openwrt-linux-uclibcgnueabi-gcc" CXX="arm-openwrt-linux-uclibcgnueabi-g++" RANLIB="arm-openwrt-linux-uclibcgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-uclibcgnueabi-strip OBJCOPY=arm-openwrt-linux-uclibcgnueabi-objcopy OBJDUMP=arm-openwrt-linux-uclibcgnueabi-objdump SIZE=arm-openwrt-linux-uclibcgnueabi-size CFLAGS="-Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft " CXXFLAGS="-Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft " CPPFLAGS="-I/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/include -I/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/include -I/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/include -I/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/include " LDFLAGS="-L/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/lib -L/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/lib -L/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  --disable-ipv6 ; fi; )
rm -f /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/.configured_*
touch /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/.configured_yyyynnnnnn
arm-openwrt-linux-uclibcgnueabi-gcc -Os -pipe -march=armv5te -mtune=arm926ej-s -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=soft -L/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/usr/lib -L/home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/lib -L/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/usr/lib -L/home/zig/chaos_calmer/staging_dir/toolchain-arm_arm926ej-s_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/lib -O -g -D LINUX -o /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec_v4.c
/home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec_v4.c: In function 'main':
/home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec_v4.c:117:17: warning: incompatible implicit declaration of built-in function 'strncpy' [enabled by default]
                 strncpy(Params,&buf[0],50);
                 ^
touch /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/.built
mkdir -p /home/zig/chaos_calmer/bin/hisilicon/packages /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec/CONTROL /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/pkginfo
install -d -m0755 /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec/usr/bin
install -m0755 /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec/usr/bin/
find /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="arm-openwrt-linux-uclibcgnueabi-" NO_RENAME=1 ; NM="arm-openwrt-linux-uclibcgnueabi-nm" STRIP="/home/zig/chaos_calmer/staging_dir/host/bin/sstrip" STRIP_KMOD="/home/zig/chaos_calmer/scripts/strip-kmod.sh" PATCHELF="/home/zig/chaos_calmer/staging_dir/host/bin/patchelf" /home/zig/chaos_calmer/scripts/rstrip.sh /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec
rstrip.sh: /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec/usr/bin/megatec: executable
(cd /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/zig/chaos_calmer/bin/hisilicon/packages/glutinium
/home/zig/chaos_calmer/scripts/ipkg-build -c -o 0 -g 0 /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec /home/zig/chaos_calmer/bin/hisilicon/packages/glutinium
Packaged contents of /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/ipkg-hisilicon/megatec into /home/zig/chaos_calmer/bin/hisilicon/packages/glutinium/megatec_2018-10-01-1_hisilicon.ipk
rm -rf /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec
mkdir -p /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/stamp /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec
install -d -m0755 /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec/usr/bin
install -m0755 /home/zig/chaos_calmer/build_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/megatec-2018-10-01/megatec /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec/usr/bin/
SHELL= /home/zig/chaos_calmer/staging_dir/host/bin/flock /home/zig/chaos_calmer/tmp/.root-copy.flock -c 'cp -fpR /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec/. /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/'
rm -rf /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/tmp-megatec
touch /home/zig/chaos_calmer/staging_dir/target-arm_arm926ej-s_uClibc-0.9.33.2_eabi/root-hisilicon/stamp/.megatec_installed
make[2]: Leaving directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
make[1]: Leaving directory `/home/zig/chaos_calmer'
make[1]: Entering directory `/home/zig/chaos_calmer'
make[2]: Entering directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
make[2]: Leaving directory `/home/zig/chaos_calmer/feeds/glutinium/megatec'
make[1]: Leaving directory `/home/zig/chaos_calmer'
