### ISSUE TITLE
Patch in i2c-hd44780 kernel module

### ISSUE THREAD

**Issue by PauloCardosoC** [ZigFisher/Glutinium#4]
Hi. I have found and patch 2 errors in "i2c-hd44780/src/lcdi2c.c"

The functions to set position and get character have problems.
Set and GET Position return switch row and column, and some time the set position don't write the column parameters.
Get character don't return the char at position row 0 column 0 and others.

I compile these module for use in one orange pi zero with armbian installed.

The changes are at line 169 and 376:

From
169:                   memaddr = (data->column + (data->row * data->organization.columns)) % LCD_BUFFER_SIZE;
376:                    lcdsetcursor(data, buf[0], buf[1]);

changed to:
169:                         memaddr = (1 + data->column + (data->row * data->organization.columns)) % LCD_BUFFER_SIZE;
376:                         lcdsetcursor(data, buf[1], buf[0]);

Thanks for your hard work. :)
Hope these help others too.

[lcdi2c.c.txt](https://github.com/ZigFisher/Glutinium/files/3145807/lcdi2c.c.txt)

**Comment by ZigFisher** [comment]
Hi !

Many thank's !

Fixed.

https://github.com/ZigFisher/Glutinium/commit/6ecd3204e59064d9b48463e9adbf616fec3e233e#diff-a0212570ec27ed01fff66ac32a6bd74f
